# Generated by Django 3.1.12 on 2021-06-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('FTE', 'Full Time Employee'), ('PTE', 'Part Time Employee'), ('PTC', 'Part Time Contractor'), ('FTC', 'Full Time Contractor')], default='FTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AnnualReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('review', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
            ],
        ),
    ]
